---
title: "Introduction"
numbered: true
bibliography: refs/thesis.bib
---
Education has historically been a central element in the functioning of welfare states by promoting access to opportunities and upward social mobility [@castles_oxford_2010]. However, the commodification of education in recent years has profoundly transformed the purpose of educational institutions [@oecd_education_2025; @brancaleone_educational_2011]. In this context, the expansion of private education has created a competitive environment with the public sector, leading, in some cases, to the perception that paying for education is synonymous with quality [@busemeyer_welfare_2020; @esping-andersen_politics_1985; @lindh_public_2015]. This phenomenon is particularly concerning in countries such as Chile, the United States, and Australia, where educational provision is primarily private [@castles_oxford_2010; @valenzuela_socioeconomic_2014; @lee_fairness_2024]. Thus, the commodification of education has led to tangible consequences, such as school segregation, but it has also changed people’s moral schemes about what is considered fair in education [@koos_moral_2019; @fourcade_moral_2007; @piketty_equality_2025; @brancaleone_educational_2011].

Although one might expect most people to support the public option—especially in countries with greater inequality—various studies have shown that some segments of the population support the private alternative and may even endorse the inequalities it generates [@lindh_public_2015]. This runs counter to general notions of redistribution and social justice, which are based on the principles of equality and equity [@walzer_spheres_2010]. In this sense, the private architecture of education has reshaped people’s sense of justice. The concept of “market justice” proposed by @lane_market_1986 is highly relevant in this context; it holds that access to education and its quality should be determined by an individual’s or a family’s ability to pay. By treating money as the guiding principle of education provision, this concept alludes to a distributive judgment but one focused on legitimizing inequalities rather than on the equitable distribution of resources, making it an essential element for understanding the cultural and institutional transformations brought about by the commodification of education.

The literature suggests that meritocracy is among the most significant factors in legitimizing inequalities, and particularly in market justice. Despite being a distributive system based on effort and talent, several studies have shown that meritocratic beliefs are linked to the acceptance of inequality, as they attribute responsibility for successes and failures primarily to individual agency, which functions as a cultural mechanism that justifies social hierarchies and diminishes the perception of the structural factors that shape individual trajectories [@darnon_belief_2018; @heuer_legitimizing_2020; @mau_inequality_2015; @mijs_unfulfillable_2016; @mijs_paradox_2021]. Now, in the field of market justice, previous research has shown a positive association between perception of meritocracy and market justice [@castillo_socialization_2024; @castillo_changes_2025; @castillo_justification_2026]. More specifically, meritocratic effort orientation has been found to be a key driver of education market justice preferences among both adults and students [@castillo_socialization_2024; @castillo_changes_2025]. In this way, meritocratic beliefs serve as auxiliary frames of reference for all individuals; however, this raises the questions: Are the frames of reference provided by meritocratic beliefs the same for everyone? Do these frames share the same type of association with market justice in education?

Although many scholars have shown interest in meritocratic beliefs, most adopt a one-dimensional perspective. For example, they often view meritocratic beliefs as mutually exclusive with those that acknowledge privileges in society, such as social and economic capital. This has significant implications for our understanding of social reality, as it prevents us from observing the multidimensional nature of meritocracy. Recognizing this, various authors have developed conceptual frameworks for studying meritocracy [@mijs_inequality_2018; @duru-bellat_whos_2012]; for example, @castillo_multidimensional_2023 proposes a novel conceptual framework that distinguishes between meritocratic factors—such as effort and talent—and factors of privilege—such as social networks and a wealthy family. Furthermore, this framework distinguishes between perceptions and preferences, allowing us to understand that meritocratic beliefs and beliefs about privilege are neither opposites nor mutually exclusive; they can coexist. However, there are caveats regarding how these meritocratic beliefs take shape and operate differently in people’s minds. Concretely, although we already know that meritocratic beliefs are compatible with structuralist or privilege-based beliefs, there is a lack of clarity about the different configurations of beliefs in people’s minds and how these groups of individuals are characterized by similar belief patterns. 

Some studies have sought to understand the diversity of meritocratic beliefs in person-centered approaches [@zhu_meritocratic_2025; @vanhootegem_worlds_2022], but their operationalizations of meritocracy do not distinguish between perceptions and preferences, limiting the scope of interpretations based on these measurements. We see there is also research that has already examined the link between meritocracy and market-oriented preferences in education, but without outlining a typology of beliefs that would allow for an appreciation of variations across groups in the relationship between these two variables [@lindh_public_2015; @castillo_socialization_2024; @castillo_changes_2025] In light of the above, I aim to contribute to this line of research based on two developments: (1) To identify different patterns of meritocratic beliefs using the conceptual framework proposed by @castillo_multidimensional_2023. (2) To analyze how these patterns of meritocratic beliefs relate to the preference for market justice in education.
 
The study of the relationship between meritocratic beliefs and market justice in education is particularly relevant in Chile, a country that has internalized market-based structures into its social services since the military dictatorship, during which education was one of the sectors that underwent extensive privatization—the foundations of which remain in place to this day [@valenzuela_socioeconomic_2014; @corvalan_mercado_2016; @bellei_problema_2025]. Furthermore, the country’s high levels of inequality are striking given its strong adherence to meritocracy, especially regarding the value placed on effort [@castillo_changes_2025]. Thus, this study aims to respond to two questions: (1) How do patterns of meritocratic beliefs manifest in terms of the number of identifiable groups and their sizes? (2) To what extent do meritocratic belief patterns influence preferences for market-based justice in education?. 

To address these issues, I use representative data from the Chilean survey EDUMERCO (N = 3470), a 2025 study that examined attitudes, emotions, and behaviors among adults aged 18 to 75 regarding inequalities and meritocracy. First, I applied latent class analysis to identify configurations of meritocratic beliefs, and then conducted ordinal logistic regression to examine the relationship between these profiles and preferences for market justice in education, while incorporating sociodemographic and socioeconomic factors. Thus, this research expands our understanding of how people’s normative judgments vary and, above all, attempts to clarify that meritocracy does not function as a one-way mechanism for legitimizing educational inequalities. This can provide an assessment of how people normatively perceive the functioning of education, which may serve as a basis for developing policies to promote educational justice.
 

