---
bibliography: refs/thesis.bib
---

## Education and legitimization of inequalities

Education is one of the core pillars of societal structure, but the role it plays has been the subject of an unresolved debate. From a theoretical perspective, education plays an ambivalent role: on the one hand, it has been argued that it promotes access to opportunities, skill development, and the reduction of social inequalities. This perspective is supported by various mechanisms, such as human capital development and/or the development of critical awareness of structural problems [@becker_human_1993; @freire_pedagogia_2015; @schultz_investment_1961]. On the other hand, education has been understood as a source of social inequalities, as it reproduces individuals’ living conditions, preventing opportunities for intergenerational social mobility and, consequently, perpetuating the stratified order. These approaches have developed primarily through theories that draw on symbolic violence and social reproduction as mechanisms for legitimizing inequalities [@bourdieu_reproduccion_2019; @bowles_schooling_2011]. Thus, education can be understood through its enlightening role in social life, but also as a cog in the reproduction of inequalities in society.

Recent literature provides empirical support for these two theoretical approaches to education. For example, research by @bubak_perceptions_2019 found that higher levels of education are negatively associated with support for meritocracy, acknowledging that structural conditions determine individual outcomes. Along the same lines, using the 2009 ISSP survey, @zhu_meritocratic_2025 found that in Finland, the enlightening effect of education was present, unlike in the United States and China. In contrast, the research by @diwan_does_2020 concluded that states deliberately use education to shape students’ political attitudes in order to reproduce national identity. Likewise, @vannoord_educationbased_2019 used data from 31 countries to show that education is widely understood as the basis for social stratification. However, the results from @liu_does_2026 suggest that education does not fulfill a generalized function; rather, both the enlightening and the reproductionist roles exist but depend on the macro context, where the enlightening role is present in countries with low levels of inequality, while the legitimizing role is observed in countries with high levels of inequality.

Besides to the functional role of education, a vast body of literature has situated education within the framework of redistributive preferences. In a cross-country study, @busemeyer_investing_2018 found that education is the policy field with the highest level of support for spending; however, when distinguishing between types of spending, higher levels of investment in private education are negatively associated with preferences for redistribution [@busemeyer_education_2013]. In country-specific studies such as those in Australia and Chile, most respondents stated that they consider it unfair for the quality of education to depend on parents’ ability to pay [@castillo_changes_2025; @lee_fairness_2024]. Furthermore, based on correlational and experimental evidence, @soler-martinez_income_2025 found that perceived educational inequality is associated with greater intolerance of inequality.  

Surveys have been the primary tool for studying educational inequalities, measuring the concept through individuals’ perceptions. In this frame, ISSP, as one of the most globally recognized surveys for measuring inequality, poses the question: *“Is it fair that high-income individuals have better education than lower-income individuals?”*. Some studies have incorporated this operationalization into national surveys [@castillo_changes_2025]. Other studies have developed questions aimed at measuring the perceived gap in educational inequality (*i.e., “In your judgment, how large or small are the differences in education between the rich and poor in Spain?”*) [@soler-martinez_income_2025]. @busemeyer_investing_2018 conducted a survey in which the focus of the question was on the distribution of education spending, rather than on the judgment of inequality: *Let’s talk about the distribution of public spending in the education sector. Please tell me whether you would like to see more or less government spending in each of the following areas. Keep in mind that ‘more’ or ‘much more’ might require a tax increase*. All operationalizations share the general objective of measuring educational inequalities, but each employs a different strategy and focuses on a distinct dimension of the concept.


