---
bibliography: refs/thesis.bib
---

## Market justice preferences

Welfare states have undergone several institutional transformations in recent years, with private expansion strongly penetrating social services alongside public provision [@busemeyer_welfare_2020]. Such processes have led to changes in the architecture of the institutions responsible for social welfare. On the one hand, private companies operate as service administrators of benefits based on the user's ability to pay, whereas on the other hand, public providers have reorganized to compete as quasi-markets [@lindh_it_2017]. Besides changes at the formal level, the commodification of social services shapes cultural norms and beliefs, where markets operate as moral projects [@fourcade_moral_2007; @koos_moral_2019]. 

Due to the processes of commodification that educational systems have undergone in recent decades, education has become one of the key dimensions in the study of market justice. The introduction of market logic into educational institutions has largely led to the loss of education’s intrinsic value in its commitment to equal opportunity, with the generation of monetary value taking precedence over everything else [@brancaleone_educational_2011; @abowitz_public_2018; @ball_education_2004; @piketty_equality_2025; @satz_why_2010]. In the Chilean context, the market has come to be seen as an inseparable element of education, to the point where it is referred to as the “education market” rather than education itself [@corvalan_mercado_2016]. The education market has been sustained over the past 50 years by the neoliberal policies implemented during the dictatorship (1973–1989), which have established the predominance of private institutions over public ones in terms of educational quality, leading to a proliferation of educational inequalities in areas such as student outcomes, school segregation, and school infrastructure, to name a few [@valenzuela_socioeconomic_2014; @ramos_educacion_2022; @canales_por_2016; @bellei_problema_2025; @bellei_gran_2016]. Consequently, the education market—where the quality of and access to education depend on how much money families have—does not allow educational opportunities to be distributed fairly.

The field of distributive justice has gradually incorporated market preferences into attitudinal research on redistribution. Since Kluegel’s seminal work [-@kluegel_beliefs_1981] on the normative foundations of beliefs about social stratification, the concept of market justice preferences has been developed, understood as the normative principle that legitimizes access to goods and services according to an individual's or family's ability to pay [@lane_market_1986]. This principle is closely linked to the justification of inequalities: by conceiving the market as a space of equal opportunities, economic success is interpreted as an individual achievement [@kluegel_legitimation_1999], disregarding the structural conditions that produce such disparities. In this way, market justice operates simultaneously as an economic and moral principle that legitimizes socioeconomic inequalities.

Most research in this field relies on survey data, in which questions about market justice directly probe support for the provision of social services—education, pensions, and health care—based on individual ability to pay (e.g., “Is it fair that high-income individuals receive better education than low-income individuals?”) [@busemeyer_education_2013; @lindh_public_2015]. Within this framework, International Social Survey Programm (ISSP) has been the primary source for advancing this agenda. Also, recent research has employed a separate analysis of each item [@castillo_changes_2025; @castillo_justification_2026], but also have been implemented indexes constructed from relevant items [@castillo_perceptions_2025]. 

Recent literature on market preferences has identified significant associations mainly at individual level. Socioeconomic status emerges as a consistent predictor; those in more advantaged positions tend to exhibit greater preferences for market justice [@koos_moral_2019; @lindh_public_2015], a pattern reflecting a moral economy that justifies status for those who benefit from the market order. In this regard, political ideology shows a clear association, with right-leaning individuals tending to favor market-oriented distributional principles [@castillo_socialization_2024; @lee_fairness_2024]. Along the same lines, meritocracy has emerged as another important factor associated with market justice, where the meritocratic narrative has been positively correlated with pro-market positions [@castillo_justification_2026; @castillo_changes_2025; @castillo_socialization_2024; @heuer_legitimizing_2020]. In this research, I focus in the individual level factors related to market justice in education, specially on meritocracy as a catalyst for justifying inequalities.