---
bibliography: refs/thesis.bib
---

## Meritocratic beliefs

When discussing education, it is difficult not to encounter the concept of meritocracy. Based on Michael Young’s work *The Rise of Meritocracy* (1962) [-@young_rise_2017], this concept is understood as the distribution of rewards based on effort and talent. For their part, schools award credentials that reflect students’ performance in various subjects. In this sense, meritocracy is a fundamental element of every educational institution, as it is one of the principles governing the awarding of credentials. Thus, beliefs about the educational system are often closely tied to meritocracy [@clycq_meritocracy_2014; @darnon_belief_2018].

In the field of education, meritocracy has been used as a distributive principle, but within this framework, it has also been linked to the justification of inequalities. Starting from Adams' theory of equity [-@adams_understanding_1963], meritocracy operates as a universal equality principle, where rewards should be commensurate with effort. Several studies have shown that meritocratic beliefs are associated with individualistic beliefs, such as an aversion to redistribution and a preference for market justice [@castillo_socialization_2024; @castillo_changes_2025; @mijs_paradox_2021; @sin_they_2026; @bartram_does_2023], and are characteristic of those in more privileged social positions [@heuer_legitimizing_2020]. In these cases, meritocracy is used to legitimize positions, with those who benefit from the system often justifying their success on the basis of their own merit, overlooking the structural conditions that shape reality. Thus, the merit narrative is used to support the idea that money should determine the quality and access to education. This normative judgment runs counter to educational justice, as it hinders equal opportunities and, ultimately, determines students’ educational trajectories [@moyano_justicia_2020; @walzer_spheres_2010].

In the meritocracy research framework, most studies have used survey items, with the International Social Survey Program as the main instrument for measuring and analyzing meritocratic beliefs in both national and international contexts. These items show the relevance of meritocratic and privilege factors for getting ahead in life, like effort and contacts, respectively. Following this conceptual model, there is a tradition of studying meritocratic beliefs from a unidimensional perspective [@garcia-sanchez_vicious_2019; @mijs_paradox_2021]. The fundamental assumption of this perspective is that the factors are negatively correlated; for example, if one expresses a higher degree of meritocratic beliefs, then, consequently, beliefs that account for structural factors decrease. The problem with this approach is that it has serious implications for understanding social reality, since people’s beliefs cannot be assumed to follow a rational logic where, if one goes up, the other must go down. To address this, in recent years, some authors have proposed a multidimensional perspective on meritocracy, constructing frameworks that allow for distinguishing the dimension of merit from that of privilege, on the one hand, and differentiating perceptions from preferences on the other [@castillo_multidimensional_2023; @duru-bellat_whos_2012; @zhu_meritocratic_2025]. These advances have led to two key contributions: (1) to capture the coexistence of beliefs that may be considered contradictory and, consequently, (2) to demonstrate that people can hold different sets of meritocratic beliefs.

While the multidimensional perspective on meritocracy allows for a more detailed examination of people’s beliefs, a caveat remains about the individuals who hold them. So far, we do not know how different combinations of these dimensions operate in people's minds or how prevalent they are in populations. Several methods have addressed these issues by estimating how variables can group into persons, with Latent Class Analysis (LCA) among the most promising approaches. LCA is a person-centered approach that allows us to identify the heterogeneity of individuals’ beliefs by clustering them, going beyond the scope of variable-centered methods, which assume that the association between two or more variables in the population behaves uniformly [@cech_perceiving_2010]. In our context, one advantage of this approach is that it accommodates the possibility that individuals may hold both meritocratic and structuralist beliefs, allowing for a theoretical and methodological examination of multidimensional meritocracy [@zhu_meritocratic_2025; @nylund-gibson_ten_2018].

Although LCA allows us to identify different configurations of meritocratic beliefs, it is not possible to define in advance the types of patterns that will be found. In this regard, the evidence suggests that one of the most common patterns is pure meritocratic beliefs, in which individuals consider merit important and structural factors unimportant [@zhu_meritocratic_2025; @xian_bootstraps_2017; @heuer_legitimizing_2020]. On the other hand, a pattern has also been identified in which success is attributed to family and background conditions rather than effort [@c.palomino_wealth_2026]. Finally, a pattern of dual consciousness has been identified, in which individuals consider merit, family connections, and wealth to be important [@zhu_meritocratic_2025]. Therefore, based on previous studies, this research hypothesizes three types of groups based on meritocratic beliefs:

$H_{1}$: **(1) purely meritocratic beliefs, viewing merits as important while deeming privilege factors as irrelevant; (2) aware of privilege beliefs, viewing privilege factors as important while deeming merits as unimportant; (3) dual consciousness, viewing merits and privilege factors as important simultaneously**.

Each pattern of meritocratic beliefs can be situated within a framework of meaning related to a preference for market justice in education. As the literature suggests, the perception of meritocracy is widely associated with the legitimization of inequalities—and specifically with market justice—so it is to be expected that the first group would adhere to this pattern [@castillo_perceptions_2025; @castillo_changes_2025]. With regard to the second group, the prevalence of privilege could be directly associated with disagreement over education-market justice preferences, since observing that society distributes rewards based on factors unrelated to merit might seem unfair [@alesina_preferences_2005]. Finally, the pattern of dual consciousness may demonstrate that the recognition of merit and privilege in the functioning of society could imply an understanding that structural conditions play an important role in individual outcomes, leading to opposition to the idea that access to and the quality of a service such as education should be based on economic conditions [@zhu_meritocratic_2025; @xian_bootstraps_2017]. Based on the above, the following hypotheses emerge:


$H_{2}$: **Purely meritocratic beliefs class shows a positive association with education market justice preferences**

$H_{3}$: **Aware of privilege beliefs class shows a negative association with education market justice preferences**

$H_{4}$: **Dual consciousness beliefs class shows a negative association with education market justice preferences**
